[package]
name = "gtk4-test"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4-layer-shell = "0.4"
gtk = { package = "gtk4", version = "0.9", features = ["v4_12", "v4_14"] }
gio = "0.20"
interval-task = "0.2.0"
serde_jsonrc = "0.1"
serde = { version = "1.0", features = ["derive"] }
xdg = "2.5.2"
clap = { version = "4.5", features = ["derive"] }
hyprland = { version = "0.4.0-alpha.2", optional = true, default-features = false, features = [
  "data",
  "async-lite",
] }
educe = { version = "0.6.0", default-features = false, features = ["Debug"] }
regex = "1.10.5"
log = "0.4.22"
env_logger = "0.11.5"
notify-rust = "4.11.0"
scopeguard = "1.2.0"
notify = "6.1.1"
async-channel = "2.3.1"
notify-debouncer-mini = "0.4.1"
cairo-rs = { version = "0.20", features = ["freetype", "freetype-rs", "png"] }
libpulse-binding = "2.28.1"
blight = "0.7.1"
zbus = "4.3.1"

[dependencies.way-edges-derive]
path = "way-edges-derive"


[features]
default = ["normal"]
hyprland = ["dep:hyprland"]
normal = []

[profile.release]
opt-level = 3 # Optimize for size
# lto = "fat"
strip = true # Strip symbols from binary*
